language: swift
osx_image: xcode10.2
cache:
  bundler: true
  directories:
    - vendor/bundle
    - Pods
  
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - bundle install

install:
  - bundle exec pod repo update
  - bundle exec pod install

before_script: 
  #- bundle exec danger 
  
script:
  - xcodebuild -workspace GOLDMEDAL.xcworkspace -scheme GOLDMEDAL -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  # - make travis

notifications:
  email: false
  slack: 
    rooms: polydice:sIHbPAtvEmpZoZiLWEYDELsC
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
